In [52]:
import numpy as np

In [53]:
#1. What is a Python library? Why do we use Python libraries?

#Answer:In my own words i can say that python library is a 
#collection of optimized functions.We use python libraries 
#because to increase the reusability and we can complete our
#task so fast.Some of the examples of important python libraries 
#are Numpy,Pandas,etc,.....

In [54]:
#2. What is the difference between Numpy array and List?

#Answer:In my point of view the main differences are:
#1) Arrays are faster than list in terms of Access and etc.
#2) Arrays store Homogenous data whereas list stores Hetrogenous data.
#3) Arrays store the data in contiguous fashion but list will not. 

In [55]:
#3. Find the shape, size and dimension of the following array?
#[[1, 2, 3, 4],
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

#Answer:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
print("Shape of the Array is ", np.shape(arr))
print("Size of the Array is ", np.size(arr))
print("Dimension of the Array is ", np.ndim(arr))

Shape of the Array is  (3, 4)
Size of the Array is  12
Dimension of the Array is  2


In [56]:
#4. Write python code to access the first row of the following array?
#[[1, 2, 3, 4],
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

#Answer:
print("Access the first row of the following array ", arr[0])

Access the first row of the following array  [1 2 3 4]


In [57]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
#[[1, 2, 3, 4],
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

#Answer:
print("Access the element at the third row and fourth column of the following array ", arr[2][3])

Access the element at the third row and fourth column of the following array  12


In [58]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
#[[1, 2, 3, 4],
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

#Answer:
print("Extract all odd-indexed elements of the following array ")
print(arr[:,1::2])

Extract all odd-indexed elements of the following array 
[[ 2  4]
 [ 6  8]
 [10 12]]


In [59]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?

#Answer:
print(np.random.random((3,3)))

[[0.55209273 0.15046768 0.20072225]
 [0.01278593 0.14143474 0.95247157]
 [0.33969075 0.95029777 0.29247033]]


In [60]:
#8. Describe the difference between np.random.rand and np.random.randn?

#Answer:
#1. np.random.rand will gives the array with elements that lie between
# 0 and 1 where 0 is included and 1 is excluded of given shape.
#2. np.random.randn will used to generate an array of random numbers 
#from a standard normal distribution 
#Examples
print(np.random.rand(3,3))
print(np.random.randn(3,3))

[[0.42893698 0.48659777 0.09252453]
 [0.17653536 0.54963347 0.31375439]
 [0.08923011 0.80285351 0.59195465]]
[[ 0.86603224 -0.44500757  0.72488594]
 [-0.75610601  0.00975276 -0.61766873]
 [ 0.07299589  0.30672805 -0.89394984]]


In [61]:
#9. Write code to increase the dimension of the following array?
#[[1, 2, 3, 4],
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

#Answer:
print(np.expand_dims(arr,axis=0))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [62]:
#10. How to transpose the following array in NumPy?
#[[1, 2, 3, 4],
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

#Answer:
print("we can use Array.T in numpy for transpose")
print(arr.T)

we can use Array.T in numpy for transpose
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [63]:
#11. Consider the following matrix:
#Matrix A: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
#Perform the following operation using Python:
#1.Index wise multiplication
#2.Matrix multiplication
#3.Add both the matrics
#4.Subtact matix B from A
#5.Divide Matrix B by A

#Answer:
A=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("1.Index wise multiplication:")
print(A*B)
print("2.Matrix multiplication:")
print("This cannot be possible because 3x4 and 3x4 4 and 3 not same so matrix multiplication is not possible")
print("To do matrix multiplication we have to do A @ B")
print("3.Add both the matrics:")
print(A+B)
print("4.Subtact matix B from A:")
print(A-B)
print("5.Divide Matrix B by A:")
print(B/A)

1.Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
2.Matrix multiplication:
This cannot be possible because 3x4 and 3x4 4 and 3 not same so matrix multiplication is not possible
To do matrix multiplication we have to do A @ B
3.Add both the matrics:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
4.Subtact matix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
5.Divide Matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [64]:
#12. Which function in Numpy can be used to swap the byte order of an array?

#Answer:
#We can use array.byteswap() to swap the byte order of an array

In [65]:
#13. What is the significance of the np.linalg.inv function?

#Answer:
#It calculates the inverse of a matrix.
#The significance of the np.linalg.inv function lies in various mathematical and computational applications, including:
#1.Solving systems of linear equations
#2.Finding solutions to optimization problems
#3.Determining matrix properties

In [66]:
#14. What does the np.reshape function do, and how is it used?

#Answer:
#The np.reshape function is used to reshape the array in any shape but the
#multiplication of shape must be equal to the size of the array
#It is used by np.reshape function by passing array and the required shape
#Example
arr1=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
print(np.reshape(arr,(12,1)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [67]:
#15. What is broadcasting in Numpy?

#Answer:
#Broadcasting in NumPy is a powerful mechanism that allows arrays of different 
#shapes to be combined in arithmetic operations. When operating on arrays of 
#different shapes, NumPy automatically broadcasts the arrays to make them 
#compatible, if possible. This means that certain operations can be performed 
#even if the arrays do not have the same shape, as long as their shapes are 
#compatible according to broadcasting rules.
#Example:
arr1=np.zeros((3,3))
arr2=np.array([1,2,3])
print(arr1+arr2)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
